GET http://127.0.0.1:5000/api/tasks

###

POST http://127.0.0.1:5000/api/tasks
Content-Type: application/json

{
    "title": "Revise algorithms"
}


###

POST http://127.0.0.1:5000/api/tasks
Content-Type: application/json

{}

###

POST http://127.0.0.1:5000/api/tasks
Content-Type: application/json

{
  "title": ""
}