GET http://127.0.0.1:5000/api/tasks

###

POST http://127.0.0.1:5000/api/tasks
Content-Type: application/json

{
    "title": "Revise algorithms"
}


###

POST http://127.0.0.1:5000/api/tasks
Content-Type: application/json

{}

###

POST http://127.0.0.1:5000/api/tasks
Content-Type: application/json

{
  "title": ""
}

###
PATCH http://127.0.0.1:5000/api/tasks/1
Content-Type: application/json

{
    "completed": true
}
###

DELETE http://127.0.0.1:5000/api/tasks/2

###

GET http://127.0.0.1:5000/api/tasks/2

###

POST http://127.0.0.1:5000/api/db-testing
Content-Type: application/json

{
    "title": "Learn SQLAlchemy"
}
###

PATCH http://127.0.0.1:5000/api/db-testing/3
Content-Type: application/json

{
    "completed": true
}

###

DELETE http://127.0.0.1:5000/api/db-testing/3

###
GET http://127.0.0.1:5000/api/db-testing/3
